---
version: "3.4"

services:
  nativefier:
    image: nativefier/nativefier:latest
    entrypoint:
      [
        "nativefier",
        "--icon",
        "/src/icon.png",
        "--name",
        "whatsApp",
        "--inject",
        "/src/whatsapp_fix.js",
        "-p",
        "linux",
        "-a",
        "x64",
        "--lang",
        "it",
        "--user-agent",
        "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/98.0",
        "--single-instance",
        "https://web.whatsapp.com/",
        "/target/",
        "--verbose"
      ]
    volumes:
      - ./custom:/src
      - ./apps:/target
